[2024-02-02T02:32:37.336+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.Companies_table_Creation manual__2024-02-02T02:25:19.171007+00:00 [queued]>
[2024-02-02T02:32:37.431+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.Companies_table_Creation manual__2024-02-02T02:25:19.171007+00:00 [queued]>
[2024-02-02T02:32:37.446+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 6
[2024-02-02T02:32:37.830+0000] {taskinstance.py:2191} INFO - Executing <Task(MySqlOperator): Companies_table_Creation> on 2024-02-02 02:25:19.171007+00:00
[2024-02-02T02:32:37.972+0000] {standard_task_runner.py:60} INFO - Started process 4729 to run task
[2024-02-02T02:32:38.200+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Read_and_load_of_API_to_MySQLDB', 'Companies_table_Creation', 'manual__2024-02-02T02:25:19.171007+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/CRM.py', '--cfg-path', '/tmp/tmpjts06to1']
[2024-02-02T02:32:38.218+0000] {standard_task_runner.py:88} INFO - Job 54: Subtask Companies_table_Creation
[2024-02-02T02:32:39.480+0000] {task_command.py:423} INFO - Running <TaskInstance: Read_and_load_of_API_to_MySQLDB.Companies_table_Creation manual__2024-02-02T02:25:19.171007+00:00 [running]> on host 648978c3a8b9
[2024-02-02T02:32:41.046+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmoc' AIRFLOW_CTX_DAG_ID='Read_and_load_of_API_to_MySQLDB' AIRFLOW_CTX_TASK_ID='Companies_table_Creation' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T02:25:19.171007+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-02T02:25:19.171007+00:00'
[2024-02-02T02:32:41.064+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS companies(
              id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
              name VARCHAR(25) NOT NULL,
              catchPhrase VARCHAR(225) NOT NULL,
              bs VARCHAR(50) NOT NULL 
            )
            
[2024-02-02T02:32:41.167+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-02-02T02:32:41.313+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-02-02T02:32:41.580+0000] {sql.py:450} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS companies(
              id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
              name VARCHAR(25) NOT NULL,
              catchPhrase VARCHAR(225) NOT NULL,
              bs VARCHAR(50) NOT NULL 
            )
            , parameters: None
[2024-02-02T02:32:41.797+0000] {sql.py:459} INFO - Rows affected: 0
[2024-02-02T02:32:41.995+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Read_and_load_of_API_to_MySQLDB, task_id=Companies_table_Creation, execution_date=20240202T022519, start_date=20240202T023237, end_date=20240202T023241
[2024-02-02T02:32:42.109+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-02T02:32:42.272+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
