[2024-02-06T03:20:29.921+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.users_table manual__2024-02-06T03:05:04.018386+00:00 [queued]>
[2024-02-06T03:20:29.987+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.users_table manual__2024-02-06T03:05:04.018386+00:00 [queued]>
[2024-02-06T03:20:29.989+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T03:20:30.054+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): users_table> on 2024-02-06 03:05:04.018386+00:00
[2024-02-06T03:20:30.077+0000] {standard_task_runner.py:60} INFO - Started process 1729 to run task
[2024-02-06T03:20:30.085+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Read_and_load_of_API_to_MySQLDB', 'users_table', 'manual__2024-02-06T03:05:04.018386+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/CRM.py', '--cfg-path', '/tmp/tmp26hh5eg8']
[2024-02-06T03:20:30.093+0000] {standard_task_runner.py:88} INFO - Job 147: Subtask users_table
[2024-02-06T03:20:30.261+0000] {task_command.py:423} INFO - Running <TaskInstance: Read_and_load_of_API_to_MySQLDB.users_table manual__2024-02-06T03:05:04.018386+00:00 [running]> on host 648978c3a8b9
[2024-02-06T03:20:30.668+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmoc' AIRFLOW_CTX_DAG_ID='Read_and_load_of_API_to_MySQLDB' AIRFLOW_CTX_TASK_ID='users_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T03:05:04.018386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T03:05:04.018386+00:00'
[2024-02-06T03:20:30.702+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-02-06T03:20:30.751+0000] {sql.py:450} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS ***_PI.users(
              id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
              name VARCHAR(25) NOT NULL,
              username VARCHAR(25) NOT NULL,
              email VARCHAR(255) NOT NULL UNIQUE,
              address VARCHAR(50),
              city_id INT,
              zipcode VARCHAR(10),
              latitud VARCHAR(20),
              longitud VARCHAR(20),
              phone VARCHAR(15),
              website VARCHAR(50),
              company_id INT,
              FOREIGN KEY (city_id) REFERENCES cities(id),
              FOREIGN KEY (company_id) REFERENCES companies(id)
            )
            , parameters: None
[2024-02-06T03:20:30.780+0000] {sql.py:459} INFO - Rows affected: 0
[2024-02-06T03:20:30.782+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T03:20:30.811+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Read_and_load_of_API_to_MySQLDB, task_id=users_table, execution_date=20240206T030504, start_date=20240206T032029, end_date=20240206T032030
[2024-02-06T03:20:30.897+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T03:20:30.979+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
