[2024-02-15T20:00:50.381+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.users_table scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-02-15T20:00:50.406+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.users_table scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-02-15T20:00:50.407+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 8
[2024-02-15T20:00:50.439+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): users_table> on 2024-02-04 00:00:00+00:00
[2024-02-15T20:00:50.447+0000] {standard_task_runner.py:60} INFO - Started process 1138 to run task
[2024-02-15T20:00:50.454+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Read_and_load_of_API_to_MySQLDB', 'users_table', 'scheduled__2024-02-04T00:00:00+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/CRM.py', '--cfg-path', '/tmp/tmp6c401fx3']
[2024-02-15T20:00:50.458+0000] {standard_task_runner.py:88} INFO - Job 321: Subtask users_table
[2024-02-15T20:00:50.574+0000] {task_command.py:423} INFO - Running <TaskInstance: Read_and_load_of_API_to_MySQLDB.users_table scheduled__2024-02-04T00:00:00+00:00 [running]> on host c35f28e50200
[2024-02-15T20:00:50.780+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmoc' AIRFLOW_CTX_DAG_ID='Read_and_load_of_API_to_MySQLDB' AIRFLOW_CTX_TASK_ID='users_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T00:00:00+00:00'
[2024-02-15T20:00:50.811+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-02-15T20:00:50.845+0000] {sql.py:450} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS ***_PI.users(
              id INT AUTO_INCREMENT  PRIMARY KEY NOT NULL,
              name VARCHAR(25) NOT NULL,
              username VARCHAR(25) NOT NULL,
              email VARCHAR(255) NOT NULL UNIQUE,
              address VARCHAR(50),
              city_id INT,
              zipcode VARCHAR(10),
              latitud VARCHAR(20),
              longitud VARCHAR(20),
              phone VARCHAR(15),
              website VARCHAR(50),
              company_id INT,
              FOREIGN KEY (city_id) REFERENCES cities(id),
              FOREIGN KEY (company_id) REFERENCES companies(id)
            );
            , parameters: None
[2024-02-15T20:00:50.867+0000] {sql.py:459} INFO - Rows affected: 0
[2024-02-15T20:00:50.870+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-15T20:00:50.907+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Read_and_load_of_API_to_MySQLDB, task_id=users_table, execution_date=20240204T000000, start_date=20240215T200050, end_date=20240215T200050
[2024-02-15T20:00:50.991+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-15T20:00:51.047+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
